services:
  - type: web
    name: nolen-bot
    runtime: python
    plan: starter

    buildCommand: pip install -r requirements.txt
    startCommand: python nolen_bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: ADMIN_ID
        value: "6330924087"

      - key: WEBHOOK_SECRET
        generateValue: true
